# Generated by Django 3.1.6 on 2021-04-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rescueclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('animal', models.CharField(max_length=10)),
                ('des', models.CharField(default='none', max_length=100)),
            ],
        ),
    ]
