# Generated by Django 3.1.6 on 2021-04-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
