# Generated by Django 3.1.6 on 2021-05-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workwithus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupclass',
            name='city',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='signupclass',
            name='lama',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='signupclass',
            name='pin',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='signupclass',
            name='state',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='signupclass',
            name='strt',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
