# Generated by Django 3.1.6 on 2021-04-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateclass',
            name='amt',
            field=models.IntegerField(default=0),
        ),
    ]
