# Generated by Django 3.1.6 on 2021-05-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportus', '0002_donateclass_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donateclass',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donateclass',
            name='state',
        ),
        migrations.AddField(
            model_name='donateclass',
            name='add',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
